### ISSUE TITLE
Windows EMD tests fail with NameError

### ISSUE THREAD

**Issue by j-s-ashley** [thaler-lab/EnergyFlow#47]
Error shown [here](https://github.com/j-s-ashley/EnergyFlow/actions/runs/9858574406/job/27220276111#step:6:4121), `name '_X0' is not defined`, results from `test_n_jobs` function on [line 67](https://github.com/thaler-lab/EnergyFlow/blob/master/energyflow/tests/test_emd.py#L67).

**Comment by j-s-ashley** [comment]
Possibly related to https://github.com/thaler-lab/Wasserstein/issues/36

**Comment by j-s-ashley** [comment]
`_X0` is defined in [line 838 of emd.py](https://github.com/thaler-lab/EnergyFlow/blob/master/energyflow/emd.py#L838) as a global variable

**Comment by j-s-ashley** [comment]
Per @henryiii's advice,
> remove the `global` and `del` statements for `_X0`, `_X1`
> add `_X0`, `_X1` to the arguments for the map, like `def _emd4map(_X0, _X1, x):`
> replace `_emd4map` with `functools.partial(_emd4map(_X0, _X1)` in https://github.com/thaler-lab/EnergyFlow/blob/c63a6185b3b91df4e61c74b097e2352a4a17f518/energyflow/emd.py#L895

**Comment by j-s-ashley** [comment]
`functools.partial(_emd4map(_X0, _X1)` results in `TypeError`.

<details>
<summary>Full error</summary>
<code>
_________________ test_n_jobs[pot-2-5-True-0.7071067811865476] _________________
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
TypeError: _emd4map() missing 1 required positional argument: 'x'
"""

The above exception was the direct cause of the following exception:

backend = 'pot', n_jobs = 2, M = 5, norm = True, R = 0.7071067811865476

    @pytest.mark.emd
    @pytest.mark.parametrize('R', [np.sqrt(2)/2, 1.0, 2])
    @pytest.mark.parametrize('norm', [True, False])
    @pytest.mark.parametrize('n_jobs, M', itertools.product([1,2,None], [5,25]))
    @pytest.mark.parametrize('backend', ['wasserstein', 'pot'])
    def test_n_jobs(backend, n_jobs, M, norm, R):
        emd, emds = (ef.emd.emd, ef.emd.emds) if backend == 'wasserstein' else (ef.emd.emd_pot, ef.emd.emds_pot)
        events = np.random.rand(nev, M, 3)
        emds1 = np.zeros((nev, nev))
        for i,ev1 in enumerate(events):
            for j in range(i):
                emds1[i,j] = emd(ev1, events[j], R=R, norm=norm)
        emds1 += emds1.T
>       emds2 = emds(events, R=R, norm=norm, verbose=0, n_jobs=n_jobs)

energyflow/tests/test_emd.py:75: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/energyflow/emd.py:895: in emds_pot
    results = pool.map(partial(_emd4map,(_X0, _X1)), local_map_args, chunksize=chunksize)
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/pool.py:367: in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <multiprocessing.pool.MapResult object at 0x16aecdbd0>, timeout = None

    def get(self, timeout=None):
        self.wait(timeout)
        if not self.ready():
            raise TimeoutError
        if self._success:
            return self._value
        else:
>           raise self._value
E           TypeError: _emd4map() missing 1 required positional argument: 'x'

/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/pool.py:774: TypeError
</code>
</details>

**Comment by j-s-ashley** [comment]
> Both
> 
> `functools.partial(_emd4map(_X0, _X1)`
> 
> and (after changing `import functools` to `from functools import partial`)
> 
> `partial(_emd4map,(_X0, _X1))`
> 
> result in `TypeError` in [CI](https://github.com/j-s-ashley/EnergyFlow/actions/runs/10165539900/job/28113569411). The final argument `x` is still expected by `_emd4map`, defined [here](https://github.com/j-s-ashley/EnergyFlow/blob/fix/no-pool-global/energyflow/emd.py#L523) as
> 
> ```
> def _emd4map(_X0, _X1, x):
>      (i, j), params = x
>      return _emd(_X0[i], _X1[j], *params)
> ```
> 
> Full error (one of a few)

Correct syntax was `partial(_emd4map,_X0, _X1)`
